<?php

########################################################################
# Extension Manager/Repository config file for ext: "commentsplus"
#
# Auto generated by Extension Builder 2011-09-07
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Comments Plus',
	'description' => 'Comments Plugin',
	'category' => 'plugin',
	'author' => 'Sebastian Michaelsen',
	'author_email' => 'michaelsen@t3seo.de',
	'author_company' => 't3seo.de',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>